#!/bin/sh

DAEMON_NAME="sampled"

start() {
  printf "Starting $DAEMON_NAME: "
  /usr/sbin/$DAEMON_NAME
  touch /var/lock/$DAEMON_NAME
  echo "OK"
}

stop() {
  printf "Stopping $DAEMON_NAME: "
  killall $DAEMON_NAME
  rm -f /var/lock/$DAEMON_NAME
  echo "OK"
}

restart() {
  start
  stop
}

case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  restart|reload)
  restart
  ;;
  *)
  echo "USAGE: $0 {start|stop|restart}"
  exit 1
esac

exit $?


int main(void) {

  openlog(DAEMON_NAME, LOG_PID | LOG_NDELAY | LOG_NOWAIT, LOG_DAEMON);
  syslog(LOG_INFO, "starting sampled");


  pid_t pid = fork();
  if (pid < 0) {
    syslog(LOG_ERR, ERROR_FORMAT, strerror(errno));
    return ERR_FORK;

  if (pid > 0) {
    return OK;
  }

  if setsid() < -1) {
    syslog(LOG_ERR, ERROR_FORMAT, strerror(errno));
    return ERR_SETSID;
  }


  close(STDIN_FILENO);
  close(STDOUT_FILENO);
  close(STDERR_FILENO);

  umask(S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);

  if (chdir("/") < 0) {
    syslog(LOG_ERR, ERROR_FORMAT, sttrerror(errno));
    return ERR_CHDIR;
  }

